variable "region_name" {
  default     = null
  description = " Region name"
  type        = string
}
variable "my_key_name" {
  default     = null
  description = "Kay Name"
  type        = string
}
variable "ami" {
  type = map

  default = {
            "us-east-1" = "ami-04505e74c0741db8d" # ubuntu 14.04 LTS
		        "us-east-2" = "ami-f63b1193" # ubuntu 14.04 LTS
		        "us-west-1" = "ami-824c4ee2" # ubuntu 14.04 LTS
	        	"us-west-2" = "ami-f2d3638a" # ubuntu 14.04 LTS
  }
}
 
variable "instance_type" {
  description = "instance type for EC2 instance"
  type = map

  default = {
    "dev" = "t2.micro"
    "test" = "t2.micro"
    "prd" = "t2.micro"

    }
}

variable "subnets" {
    default     = null
  description = "DB identifier prefix (will be generated by AWS automatically if not specified)"
  type        = string
}
variable "security_group" {
  default     = null
  description = "Security Group Name"
  type        = string
}
variable "environment" {
  default     = null
  description = "Infrastructure Environment Dev/Prd"
  type        = string
}
variable "application_type" {
  default     = null
  description = "Application Type Web/App"
  type        = string
}
variable "vpc-name" {
  default     = null
  description = "VPC Name"
  type        = string
}
#variable "instance_profile" {}
